"""market place

Revision ID: 13257ab77ca0
Revises: 
Create Date: 2022-08-16 19:14:06.457734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13257ab77ca0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockchain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('live', 'alpha', 'beta', name='statusenum'), nullable=True),
    sa.Column('sustainability_score', sa.Integer(), nullable=True),
    sa.Column('decentralization_score', sa.Integer(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blockchain_id'), 'blockchain', ['id'], unique=False)
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('icon', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_table('deployment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_id'), 'deployment', ['id'], unique=False)
    op.create_table('protocol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocol_id'), 'protocol', ['id'], unique=False)
    op.create_table('server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('recommended', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_id'), 'server', ['id'], unique=False)
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('server', 'deployment', name='typeenum'), nullable=True),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('billing_cycle', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=45), nullable=False),
    sa.Column('currency_icon', sa.Text(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_id'), 'service', ['id'], unique=False)
    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('recommended', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_id'), 'site', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('whmcs_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=45), nullable=False),
    sa.Column('firstname', sa.String(length=45), nullable=True),
    sa.Column('lastname', sa.String(length=45), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('BlockchainCategory',
    sa.Column('blockchain_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blockchain_id'], ['blockchain.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], )
    )
    op.create_table('blockchain_deployment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blockchain_id', sa.Integer(), nullable=False),
    sa.Column('deployment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blockchain_id'], ['blockchain.id'], ),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blockchain_deployment_id'), 'blockchain_deployment', ['id'], unique=False)
    op.create_table('blockchain_protocol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blockchain_id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blockchain_id'], ['blockchain.id'], ),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blockchain_protocol_id'), 'blockchain_protocol', ['id'], unique=False)
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('billing_cycle', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_id'), 'purchase', ['id'], unique=False)
    op.create_table('server_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_site_id'), 'server_site', ['id'], unique=False)
    op.create_table('starting_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=45), nullable=False),
    sa.Column('currency_icon', sa.Text(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('blockchain_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blockchain_id'], ['blockchain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_starting_price_id'), 'starting_price', ['id'], unique=False)
    op.create_table('blockchain_deployment_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blockchain_deployment_id', sa.Integer(), nullable=False),
    sa.Column('blockchain_protocol_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blockchain_deployment_id'], ['blockchain_deployment.id'], ),
    sa.ForeignKeyConstraint(['blockchain_protocol_id'], ['blockchain_protocol.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blockchain_deployment_price_id'), 'blockchain_deployment_price', ['id'], unique=False)
    op.create_table('purchase_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_service_id'), 'purchase_service', ['id'], unique=False)
    op.create_table('server_site_price',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_site_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['server_site_id'], ['server_site.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_site_price_id'), 'server_site_price', ['id'], unique=False)
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_id'), 'subscription', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_id'), table_name='subscription')
    op.drop_table('subscription')
    op.drop_index(op.f('ix_server_site_price_id'), table_name='server_site_price')
    op.drop_table('server_site_price')
    op.drop_index(op.f('ix_purchase_service_id'), table_name='purchase_service')
    op.drop_table('purchase_service')
    op.drop_index(op.f('ix_blockchain_deployment_price_id'), table_name='blockchain_deployment_price')
    op.drop_table('blockchain_deployment_price')
    op.drop_index(op.f('ix_starting_price_id'), table_name='starting_price')
    op.drop_table('starting_price')
    op.drop_index(op.f('ix_server_site_id'), table_name='server_site')
    op.drop_table('server_site')
    op.drop_index(op.f('ix_purchase_id'), table_name='purchase')
    op.drop_table('purchase')
    op.drop_index(op.f('ix_blockchain_protocol_id'), table_name='blockchain_protocol')
    op.drop_table('blockchain_protocol')
    op.drop_index(op.f('ix_blockchain_deployment_id'), table_name='blockchain_deployment')
    op.drop_table('blockchain_deployment')
    op.drop_table('BlockchainCategory')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_site_id'), table_name='site')
    op.drop_table('site')
    op.drop_index(op.f('ix_service_id'), table_name='service')
    op.drop_table('service')
    op.drop_index(op.f('ix_server_id'), table_name='server')
    op.drop_table('server')
    op.drop_index(op.f('ix_protocol_id'), table_name='protocol')
    op.drop_table('protocol')
    op.drop_index(op.f('ix_deployment_id'), table_name='deployment')
    op.drop_table('deployment')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_blockchain_id'), table_name='blockchain')
    op.drop_table('blockchain')
    # ### end Alembic commands ###
